# Configuration settings

annotation_path: /kaggle/input/face-mask-detection/annotations
image_path: /kaggle/input/face-mask-detection/images

label_map:
  with_mask: 0
  without_mask: 1
  mask_weared_incorrect: 2

target_size: [224, 224] #Example
batch_size: 32 #Example
learning_rate: 0.001 #Example