# Configuration settings

kaggle_dataset: andrewmvd/face-mask-detection

label_map:
  with_mask: 0
  without_mask: 1
  mask_weared_incorrect: 2

num_classes: 3
target_size: [224, 224] 
batch_size: 32 
learning_rate: 0.001
num_epochs: 10
patience: 4

best_model_path: models/final/face_mask_detector_version01.pth

model_name: face_mask_detector_version01.pth

repo_id: lijoraju/face_mask_detector_model